//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmpAutoTunerUtility.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rigEnabled {
            get {
                return ((bool)(this["rigEnabled"]));
            }
            set {
                this["rigEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string tolTune {
            get {
                return ((string)(this["tolTune"]));
            }
            set {
                this["tolTune"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TunerCom {
            get {
                return ((string)(this["TunerCom"]));
            }
            set {
                this["TunerCom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TunerBaud {
            get {
                return ((string)(this["TunerBaud"]));
            }
            set {
                this["TunerBaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay1Com {
            get {
                return ((string)(this["Relay1Com"]));
            }
            set {
                this["Relay1Com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay1Baud {
            get {
                return ((string)(this["Relay1Baud"]));
            }
            set {
                this["Relay1Baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Relay1Enabled {
            get {
                return ((bool)(this["Relay1Enabled"]));
            }
            set {
                this["Relay1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay1On {
            get {
                return ((string)(this["Relay1On"]));
            }
            set {
                this["Relay1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay1Off {
            get {
                return ((string)(this["Relay1Off"]));
            }
            set {
                this["Relay1Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay1Status {
            get {
                return ((string)(this["Relay1Status"]));
            }
            set {
                this["Relay1Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay2Com {
            get {
                return ((string)(this["Relay2Com"]));
            }
            set {
                this["Relay2Com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay2Baud {
            get {
                return ((string)(this["Relay2Baud"]));
            }
            set {
                this["Relay2Baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Relay2Enabled {
            get {
                return ((bool)(this["Relay2Enabled"]));
            }
            set {
                this["Relay2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay2On {
            get {
                return ((string)(this["Relay2On"]));
            }
            set {
                this["Relay2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay2Off {
            get {
                return ((string)(this["Relay2Off"]));
            }
            set {
                this["Relay2Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay2Status {
            get {
                return ((string)(this["Relay2Status"]));
            }
            set {
                this["Relay2Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay3Com {
            get {
                return ((string)(this["Relay3Com"]));
            }
            set {
                this["Relay3Com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay3Baud {
            get {
                return ((string)(this["Relay3Baud"]));
            }
            set {
                this["Relay3Baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Relay3Enabled {
            get {
                return ((bool)(this["Relay3Enabled"]));
            }
            set {
                this["Relay3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay3On {
            get {
                return ((string)(this["Relay3On"]));
            }
            set {
                this["Relay3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay3Off {
            get {
                return ((string)(this["Relay3Off"]));
            }
            set {
                this["Relay3Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay3Status {
            get {
                return ((string)(this["Relay3Status"]));
            }
            set {
                this["Relay3Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay4Com {
            get {
                return ((string)(this["Relay4Com"]));
            }
            set {
                this["Relay4Com"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay4Baud {
            get {
                return ((string)(this["Relay4Baud"]));
            }
            set {
                this["Relay4Baud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Relay4Enabled {
            get {
                return ((bool)(this["Relay4Enabled"]));
            }
            set {
                this["Relay4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay4On {
            get {
                return ((string)(this["Relay4On"]));
            }
            set {
                this["Relay4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay4Off {
            get {
                return ((string)(this["Relay4Off"]));
            }
            set {
                this["Relay4Off"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Relay4Status {
            get {
                return ((string)(this["Relay4Status"]));
            }
            set {
                this["Relay4Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BandTolerance {
            get {
                return ((string)(this["BandTolerance"]));
            }
            set {
                this["BandTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TunerEnabled {
            get {
                return ((bool)(this["TunerEnabled"]));
            }
            set {
                this["TunerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TunerModel {
            get {
                return ((string)(this["TunerModel"]));
            }
            set {
                this["TunerModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Location {
            get {
                return ((global::System.Drawing.Point)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VFOA {
            get {
                return ((bool)(this["VFOA"]));
            }
            set {
                this["VFOA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VFOB {
            get {
                return ((bool)(this["VFOB"]));
            }
            set {
                this["VFOB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TunerSensitivity {
            get {
                return ((int)(this["TunerSensitivity"]));
            }
            set {
                this["TunerSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string textBoxAntennaFreq1From {
            get {
                return ((string)(this["textBoxAntennaFreq1From"]));
            }
            set {
                this["textBoxAntennaFreq1From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string textBoxAntennaFreq2From {
            get {
                return ((string)(this["textBoxAntennaFreq2From"]));
            }
            set {
                this["textBoxAntennaFreq2From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string textBoxAntennaFreq3From {
            get {
                return ((string)(this["textBoxAntennaFreq3From"]));
            }
            set {
                this["textBoxAntennaFreq3From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq4From {
            get {
                return ((string)(this["textBoxAntennaFreq4From"]));
            }
            set {
                this["textBoxAntennaFreq4From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq5From {
            get {
                return ((string)(this["textBoxAntennaFreq5From"]));
            }
            set {
                this["textBoxAntennaFreq5From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq6From {
            get {
                return ((string)(this["textBoxAntennaFreq6From"]));
            }
            set {
                this["textBoxAntennaFreq6From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq7From {
            get {
                return ((string)(this["textBoxAntennaFreq7From"]));
            }
            set {
                this["textBoxAntennaFreq7From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq8From {
            get {
                return ((string)(this["textBoxAntennaFreq8From"]));
            }
            set {
                this["textBoxAntennaFreq8From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string textBoxAntennaFreq1To {
            get {
                return ((string)(this["textBoxAntennaFreq1To"]));
            }
            set {
                this["textBoxAntennaFreq1To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18.17")]
        public string textBoxAntennaFreq2To {
            get {
                return ((string)(this["textBoxAntennaFreq2To"]));
            }
            set {
                this["textBoxAntennaFreq2To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public string textBoxAntennaFreq3To {
            get {
                return ((string)(this["textBoxAntennaFreq3To"]));
            }
            set {
                this["textBoxAntennaFreq3To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq4To {
            get {
                return ((string)(this["textBoxAntennaFreq4To"]));
            }
            set {
                this["textBoxAntennaFreq4To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq5To {
            get {
                return ((string)(this["textBoxAntennaFreq5To"]));
            }
            set {
                this["textBoxAntennaFreq5To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq6To {
            get {
                return ((string)(this["textBoxAntennaFreq6To"]));
            }
            set {
                this["textBoxAntennaFreq6To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq7To {
            get {
                return ((string)(this["textBoxAntennaFreq7To"]));
            }
            set {
                this["textBoxAntennaFreq7To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntennaFreq8To {
            get {
                return ((string)(this["textBoxAntennaFreq8To"]));
            }
            set {
                this["textBoxAntennaFreq8To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna1 {
            get {
                return ((bool)(this["checkBoxAntenna1"]));
            }
            set {
                this["checkBoxAntenna1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna2 {
            get {
                return ((bool)(this["checkBoxAntenna2"]));
            }
            set {
                this["checkBoxAntenna2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna3 {
            get {
                return ((bool)(this["checkBoxAntenna3"]));
            }
            set {
                this["checkBoxAntenna3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna4 {
            get {
                return ((bool)(this["checkBoxAntenna4"]));
            }
            set {
                this["checkBoxAntenna4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna5 {
            get {
                return ((bool)(this["checkBoxAntenna5"]));
            }
            set {
                this["checkBoxAntenna5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna6 {
            get {
                return ((bool)(this["checkBoxAntenna6"]));
            }
            set {
                this["checkBoxAntenna6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna7 {
            get {
                return ((bool)(this["checkBoxAntenna7"]));
            }
            set {
                this["checkBoxAntenna7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxAntenna8 {
            get {
                return ((bool)(this["checkBoxAntenna8"]));
            }
            set {
                this["checkBoxAntenna8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Antenna")]
        public string textBoxAntenna1 {
            get {
                return ((string)(this["textBoxAntenna1"]));
            }
            set {
                this["textBoxAntenna1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17M Loop Example")]
        public string textBoxAntenna2 {
            get {
                return ((string)(this["textBoxAntenna2"]));
            }
            set {
                this["textBoxAntenna2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cobweb Example")]
        public string textBoxAntenna3 {
            get {
                return ((string)(this["textBoxAntenna3"]));
            }
            set {
                this["textBoxAntenna3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntenna4 {
            get {
                return ((string)(this["textBoxAntenna4"]));
            }
            set {
                this["textBoxAntenna4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntenna5 {
            get {
                return ((string)(this["textBoxAntenna5"]));
            }
            set {
                this["textBoxAntenna5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntenna6 {
            get {
                return ((string)(this["textBoxAntenna6"]));
            }
            set {
                this["textBoxAntenna6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntenna7 {
            get {
                return ((string)(this["textBoxAntenna7"]));
            }
            set {
                this["textBoxAntenna7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxAntenna8 {
            get {
                return ((string)(this["textBoxAntenna8"]));
            }
            set {
                this["textBoxAntenna8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna1Relay {
            get {
                return ((string)(this["comboBoxAntenna1Relay"]));
            }
            set {
                this["comboBoxAntenna1Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna2Relay {
            get {
                return ((string)(this["comboBoxAntenna2Relay"]));
            }
            set {
                this["comboBoxAntenna2Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna3Relay {
            get {
                return ((string)(this["comboBoxAntenna3Relay"]));
            }
            set {
                this["comboBoxAntenna3Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna4Relay {
            get {
                return ((string)(this["comboBoxAntenna4Relay"]));
            }
            set {
                this["comboBoxAntenna4Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna5Relay {
            get {
                return ((string)(this["comboBoxAntenna5Relay"]));
            }
            set {
                this["comboBoxAntenna5Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna6Relay {
            get {
                return ((string)(this["comboBoxAntenna6Relay"]));
            }
            set {
                this["comboBoxAntenna6Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna7Relay {
            get {
                return ((string)(this["comboBoxAntenna7Relay"]));
            }
            set {
                this["comboBoxAntenna7Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAntenna8Relay {
            get {
                return ((string)(this["comboBoxAntenna8Relay"]));
            }
            set {
                this["comboBoxAntenna8Relay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string textBoxAntenna1Bits {
            get {
                return ((string)(this["textBoxAntenna1Bits"]));
            }
            set {
                this["textBoxAntenna1Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string textBoxAntenna2Bits {
            get {
                return ((string)(this["textBoxAntenna2Bits"]));
            }
            set {
                this["textBoxAntenna2Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string textBoxAntenna3Bits {
            get {
                return ((string)(this["textBoxAntenna3Bits"]));
            }
            set {
                this["textBoxAntenna3Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string textBoxAntenna4Bits {
            get {
                return ((string)(this["textBoxAntenna4Bits"]));
            }
            set {
                this["textBoxAntenna4Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string textBoxAntenna5Bits {
            get {
                return ((string)(this["textBoxAntenna5Bits"]));
            }
            set {
                this["textBoxAntenna5Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string textBoxAntenna6Bits {
            get {
                return ((string)(this["textBoxAntenna6Bits"]));
            }
            set {
                this["textBoxAntenna6Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string textBoxAntenna7Bits {
            get {
                return ((string)(this["textBoxAntenna7Bits"]));
            }
            set {
                this["textBoxAntenna7Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string textBoxAntenna8Bits {
            get {
                return ((string)(this["textBoxAntenna8Bits"]));
            }
            set {
                this["textBoxAntenna8Bits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonAntennaWire3 {
            get {
                return ((bool)(this["radioButtonAntennaWire3"]));
            }
            set {
                this["radioButtonAntennaWire3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonAntennaWire8 {
            get {
                return ((bool)(this["radioButtonAntennaWire8"]));
            }
            set {
                this["radioButtonAntennaWire8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxPTTEnabled {
            get {
                return ((bool)(this["checkBoxPTTEnabled"]));
            }
            set {
                this["checkBoxPTTEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxToneEnabled {
            get {
                return ((bool)(this["checkBoxToneEnabled"]));
            }
            set {
                this["checkBoxToneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string comboBoxAudioOut {
            get {
                return ((string)(this["comboBoxAudioOut"]));
            }
            set {
                this["comboBoxAudioOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool powerSDR {
            get {
                return ((bool)(this["powerSDR"]));
            }
            set {
                this["powerSDR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power1From {
            get {
                return ((string)(this["Power1From"]));
            }
            set {
                this["Power1From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power2From {
            get {
                return ((string)(this["Power2From"]));
            }
            set {
                this["Power2From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power3From {
            get {
                return ((string)(this["Power3From"]));
            }
            set {
                this["Power3From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power4From {
            get {
                return ((string)(this["Power4From"]));
            }
            set {
                this["Power4From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power5From {
            get {
                return ((string)(this["Power5From"]));
            }
            set {
                this["Power5From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power6From {
            get {
                return ((string)(this["Power6From"]));
            }
            set {
                this["Power6From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power7From {
            get {
                return ((string)(this["Power7From"]));
            }
            set {
                this["Power7From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Power8From {
            get {
                return ((string)(this["Power8From"]));
            }
            set {
                this["Power8From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power1To {
            get {
                return ((string)(this["Power1To"]));
            }
            set {
                this["Power1To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power2To {
            get {
                return ((string)(this["Power2To"]));
            }
            set {
                this["Power2To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power3To {
            get {
                return ((string)(this["Power3To"]));
            }
            set {
                this["Power3To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power4To {
            get {
                return ((string)(this["Power4To"]));
            }
            set {
                this["Power4To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power5To {
            get {
                return ((string)(this["Power5To"]));
            }
            set {
                this["Power5To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power6To {
            get {
                return ((string)(this["Power6To"]));
            }
            set {
                this["Power6To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power7To {
            get {
                return ((string)(this["Power7To"]));
            }
            set {
                this["Power7To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string Power8To {
            get {
                return ((string)(this["Power8To"]));
            }
            set {
                this["Power8To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power1Enabled {
            get {
                return ((bool)(this["Power1Enabled"]));
            }
            set {
                this["Power1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power2Enabled {
            get {
                return ((bool)(this["Power2Enabled"]));
            }
            set {
                this["Power2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power3Enabled {
            get {
                return ((bool)(this["Power3Enabled"]));
            }
            set {
                this["Power3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power4Enabled {
            get {
                return ((bool)(this["Power4Enabled"]));
            }
            set {
                this["Power4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power5Enabled {
            get {
                return ((bool)(this["Power5Enabled"]));
            }
            set {
                this["Power5Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power6Enabled {
            get {
                return ((bool)(this["Power6Enabled"]));
            }
            set {
                this["Power6Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power7Enabled {
            get {
                return ((bool)(this["Power7Enabled"]));
            }
            set {
                this["Power7Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Power8Enabled {
            get {
                return ((bool)(this["Power8Enabled"]));
            }
            set {
                this["Power8Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power1Watts {
            get {
                return ((string)(this["Power1Watts"]));
            }
            set {
                this["Power1Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power2Watts {
            get {
                return ((string)(this["Power2Watts"]));
            }
            set {
                this["Power2Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power3Watts {
            get {
                return ((string)(this["Power3Watts"]));
            }
            set {
                this["Power3Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power4Watts {
            get {
                return ((string)(this["Power4Watts"]));
            }
            set {
                this["Power4Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power5Watts {
            get {
                return ((string)(this["Power5Watts"]));
            }
            set {
                this["Power5Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power6Watts {
            get {
                return ((string)(this["Power6Watts"]));
            }
            set {
                this["Power6Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power7Watts {
            get {
                return ((string)(this["Power7Watts"]));
            }
            set {
                this["Power7Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Power8Watts {
            get {
                return ((string)(this["Power8Watts"]));
            }
            set {
                this["Power8Watts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power1Mode {
            get {
                return ((string)(this["Power1Mode"]));
            }
            set {
                this["Power1Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power2Mode {
            get {
                return ((string)(this["Power2Mode"]));
            }
            set {
                this["Power2Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power3Mode {
            get {
                return ((string)(this["Power3Mode"]));
            }
            set {
                this["Power3Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power4Mode {
            get {
                return ((string)(this["Power4Mode"]));
            }
            set {
                this["Power4Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power5Mode {
            get {
                return ((string)(this["Power5Mode"]));
            }
            set {
                this["Power5Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power6Mode {
            get {
                return ((string)(this["Power6Mode"]));
            }
            set {
                this["Power6Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power7Mode {
            get {
                return ((string)(this["Power7Mode"]));
            }
            set {
                this["Power7Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any")]
        public string Power8Mode {
            get {
                return ((string)(this["Power8Mode"]));
            }
            set {
                this["Power8Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string NumRelays {
            get {
                return ((string)(this["NumRelays"]));
            }
            set {
                this["NumRelays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxAntennaTab {
            get {
                return ((bool)(this["checkBoxAntennaTab"]));
            }
            set {
                this["checkBoxAntennaTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxPowerTab {
            get {
                return ((bool)(this["checkBoxPowerTab"]));
            }
            set {
                this["checkBoxPowerTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxDebugTab {
            get {
                return ((bool)(this["checkBoxDebugTab"]));
            }
            set {
                this["checkBoxDebugTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkBoxTunerTab {
            get {
                return ((bool)(this["checkBoxTunerTab"]));
            }
            set {
                this["checkBoxTunerTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkedMenuRelay1 {
            get {
                return ((bool)(this["checkedMenuRelay1"]));
            }
            set {
                this["checkedMenuRelay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedMenuRelay2 {
            get {
                return ((bool)(this["checkedMenuRelay2"]));
            }
            set {
                this["checkedMenuRelay2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedMenuRelay3 {
            get {
                return ((bool)(this["checkedMenuRelay3"]));
            }
            set {
                this["checkedMenuRelay3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkedMenuRelay4 {
            get {
                return ((bool)(this["checkedMenuRelay4"]));
            }
            set {
                this["checkedMenuRelay4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune1Power {
            get {
                return ((string)(this["Tune1Power"]));
            }
            set {
                this["Tune1Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune2Power {
            get {
                return ((string)(this["Tune2Power"]));
            }
            set {
                this["Tune2Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune3Power {
            get {
                return ((string)(this["Tune3Power"]));
            }
            set {
                this["Tune3Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune4Power {
            get {
                return ((string)(this["Tune4Power"]));
            }
            set {
                this["Tune4Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune5Power {
            get {
                return ((string)(this["Tune5Power"]));
            }
            set {
                this["Tune5Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune6Power {
            get {
                return ((string)(this["Tune6Power"]));
            }
            set {
                this["Tune6Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune7Power {
            get {
                return ((string)(this["Tune7Power"]));
            }
            set {
                this["Tune7Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Tune8Power {
            get {
                return ((string)(this["Tune8Power"]));
            }
            set {
                this["Tune8Power"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DebugLevel {
            get {
                return ((string)(this["DebugLevel"]));
            }
            set {
                this["DebugLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point LocationMain {
            get {
                return ((global::System.Drawing.Point)(this["LocationMain"]));
            }
            set {
                this["LocationMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("405, 297")]
        public global::System.Drawing.Size SizeMain {
            get {
                return ((global::System.Drawing.Size)(this["SizeMain"]));
            }
            set {
                this["SizeMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MaximizedMain {
            get {
                return ((bool)(this["MaximizedMain"]));
            }
            set {
                this["MaximizedMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizedMain {
            get {
                return ((bool)(this["MinimizedMain"]));
            }
            set {
                this["MinimizedMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PostPttDelay {
            get {
                return ((decimal)(this["PostPttDelay"]));
            }
            set {
                this["PostPttDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp1 {
            get {
                return ((bool)(this["Amp1"]));
            }
            set {
                this["Amp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp2 {
            get {
                return ((bool)(this["Amp2"]));
            }
            set {
                this["Amp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp3 {
            get {
                return ((bool)(this["Amp3"]));
            }
            set {
                this["Amp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp4 {
            get {
                return ((bool)(this["Amp4"]));
            }
            set {
                this["Amp4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp5 {
            get {
                return ((bool)(this["Amp5"]));
            }
            set {
                this["Amp5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp6 {
            get {
                return ((bool)(this["Amp6"]));
            }
            set {
                this["Amp6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp7 {
            get {
                return ((bool)(this["Amp7"]));
            }
            set {
                this["Amp7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Amp8 {
            get {
                return ((bool)(this["Amp8"]));
            }
            set {
                this["Amp8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect1 {
            get {
                return ((string)(this["AntSelect1"]));
            }
            set {
                this["AntSelect1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect2 {
            get {
                return ((string)(this["AntSelect2"]));
            }
            set {
                this["AntSelect2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect3 {
            get {
                return ((string)(this["AntSelect3"]));
            }
            set {
                this["AntSelect3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect4 {
            get {
                return ((string)(this["AntSelect4"]));
            }
            set {
                this["AntSelect4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect5 {
            get {
                return ((string)(this["AntSelect5"]));
            }
            set {
                this["AntSelect5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect6 {
            get {
                return ((string)(this["AntSelect6"]));
            }
            set {
                this["AntSelect6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect7 {
            get {
                return ((string)(this["AntSelect7"]));
            }
            set {
                this["AntSelect7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AntSelect8 {
            get {
                return ((string)(this["AntSelect8"]));
            }
            set {
                this["AntSelect8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WalkAntenna {
            get {
                return ((int)(this["WalkAntenna"]));
            }
            set {
                this["WalkAntenna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrequencyWalkList {
            get {
                return ((string)(this["FrequencyWalkList"]));
            }
            set {
                this["FrequencyWalkList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmpBits {
            get {
                return ((string)(this["AmpBits"]));
            }
            set {
                this["AmpBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp1 {
            get {
                return ((bool)(this["AntennaAmp1"]));
            }
            set {
                this["AntennaAmp1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp2 {
            get {
                return ((bool)(this["AntennaAmp2"]));
            }
            set {
                this["AntennaAmp2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp3 {
            get {
                return ((bool)(this["AntennaAmp3"]));
            }
            set {
                this["AntennaAmp3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp4 {
            get {
                return ((bool)(this["AntennaAmp4"]));
            }
            set {
                this["AntennaAmp4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp5 {
            get {
                return ((bool)(this["AntennaAmp5"]));
            }
            set {
                this["AntennaAmp5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp6 {
            get {
                return ((bool)(this["AntennaAmp6"]));
            }
            set {
                this["AntennaAmp6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp7 {
            get {
                return ((bool)(this["AntennaAmp7"]));
            }
            set {
                this["AntennaAmp7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaAmp8 {
            get {
                return ((bool)(this["AntennaAmp8"]));
            }
            set {
                this["AntennaAmp8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimerFreqWalkSeconds {
            get {
                return ((int)(this["TimerFreqWalkSeconds"]));
            }
            set {
                this["TimerFreqWalkSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClockIsZulu {
            get {
                return ((bool)(this["ClockIsZulu"]));
            }
            set {
                this["ClockIsZulu"] = value;
            }
        }
    }
}
